apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: myappserver
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-volume
              mountPath: /app
            - name: config-volume
              mountPath: /etc/postgresql
              readOnly: true
            - name: secret-volume
              mountPath: /etc/postgresql/secrets
              readOnly: true
          command: ["/bin/bash"]
          args: ["-c", "cat /etc/postgresql/postgresql.conf && cat /etc/postgresql/pg_hba.conf && echo $POSTGRES_PASSWORD > /etc/postgresql/secrets/pgpassword"]
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: app-files
        - name: config-volume
          configMap:
            name: pg-config
        - name: secret-volume
          secret:
            secretName: pg-secrets
