version: "3.9"

services:
  db:
    build: .
    container_name: my-database
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build: .
    container_name: my-webapp
    ports:
      - "8000:8080"
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  dbdata:
