apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lottery.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - secretName: {{ include "lottery.ingress.tls.secretName" . }}
      hosts:
        - {{ .Values.ingress.hosts | first }}
  rules:
    - host: {{ .Values.ingress.hosts | first }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "lottery.fullname" . }}
                port:
                  name: http
