apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lottery.persistence.claimName" . }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
