apiVersion: v1
kind: Service
metadata:
  name: {{ include "lottery.fullname" . }}
  annotations:
    key1: value1
    key2: value2
spec:
  selector:
    app: {{ include "lottery.name" . }}
  ports:
    - name: http
      port: 80
      nodePort: 30001
      protocol: TCP
  type: NodePort
