apiVersion: v1
kind: Pod
metadata:
  name: django-app-pod
  labels:
    app: django-app
spec:
  containers:
    - name: django-app
      image: <your-docker-image-name>
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: app-volume
          mountPath: /app
  volumes:
    - name: app-volume
      persistentVolumeClaim:
        claimName: app-pvc
