apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/kali/Desktop/ticket_app/ticket_app/
