# Generated by Django 3.2.15 on 2023-04-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawresult',
            name='winning_numbers',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
